module.exports = {
    UPDATE_ANALOG_INPUT: 'UPDATE_ANALOG_INPUT',
    UPDATE_ANALOG_OUTPUT: 'UPDATE_ANALOG_OUTPUT',
    UPDATE_ANALOG_VALUE: 'UPDATE_ANALOG_VALUE',
    UPDATE_BINARY_INPUT: 'UPDATE_BINARY_INPUT',
    UPDATE_BINARY_OUTPUT: 'UPDATE_BINARY_OUTPUT',
    UPDATE_BINARY_VALUE: 'UPDATE_BINARY_VALUE',
};