module.exports = {
    CREATE_ANALOG_INPUTS: 'CREATE_ANALOG_INPUTS',
    CREATE_ANALOG_OUTPUT: 'CREATE_ANALOG_OUTPUT',
    CREATE_ANALOG_VALUE: 'CREATE_ANALOG_VALUE',
    CREATE_BINARY_INPUT: 'CREATE_BINARY_INPUT',
    CREATE_BINARY_OUTPUT: 'CREATE_BINARY_OUTPUT',
    CREATE_BINARY_VALUE: 'CREATE_BINARY_VALUE',
    UPDATE_ANALOG_INPUT: 'UPDATE_ANALOG_INPUT',
    UPDATE_ANALOG_OUTPUT: 'UPDATE_ANALOG_OUTPUT',
    UPDATE_ANALOG_VALUE: 'UPDATE_ANALOG_VALUE',
    UPDATE_BINARY_INPUT: 'UPDATE_BINARY_INPUT',
    UPDATE_BINARY_OUTPUT: 'UPDATE_BINARY_OUTPUT',
    UPDATE_BINARY_VALUE: 'UPDATE_BINARY_VALUE',
};