export const CONNECT = 'connect';
export const UPDATE_ANALOG_INPUT = 'UPDATE_ANALOG_INPUT';
export const UPDATE_ANALOG_OUTPUT = 'UPDATE_ANALOG_OUTPUT';
export const UPDATE_ANALOG_VALUE = 'UPDATE_ANALOG_VALUE';
export const UPDATE_BINARY_INPUT = 'UPDATE_BINARY_INPUT';
export const UPDATE_BINARY_OUTPUT = 'UPDATE_BINARY_OUTPUT';
export const UPDATE_BINARY_VALUE = 'UPDATE_BINARY_VALUE';
