export const CONNECT = 'connect';
export const CREATE_ANALOG_INPUTS = 'CREATE_ANALOG_INPUTS';
export const CREATE_ANALOG_OUTPUT = 'CREATE_ANALOG_OUTPUT';
export const CREATE_ANALOG_VALUE = 'CREATE_ANALOG_VALUE';
export const CREATE_BINARY_INPUT = 'CREATE_BINARY_INPUT';
export const CREATE_BINARY_OUTPUT = 'CREATE_BINARY_OUTPUT';
export const CREATE_BINARY_VALUE = 'CREATE_BINARY_VALUE';
export const CREATE_MODBUS_VALUES = 'CREATE_MODBUS_VALUES';

export const UPDATE_ANALOG_INPUT = 'UPDATE_ANALOG_INPUT';
export const UPDATE_ANALOG_OUTPUT = 'UPDATE_ANALOG_OUTPUT';
export const UPDATE_ANALOG_VALUE = 'UPDATE_ANALOG_VALUE';
export const UPDATE_BINARY_INPUT = 'UPDATE_BINARY_INPUT';
export const UPDATE_BINARY_OUTPUT = 'UPDATE_BINARY_OUTPUT';
export const UPDATE_BINARY_VALUE = 'UPDATE_BINARY_VALUE';
export const UPDATE_MODBUS_VALUE = 'UPDATE_MODBUS_VALUE';

export const WRITE_ANALOG_VALUE = 'WRITE_ANALOG_VALUE';
export const WRITE_ANALOG_OUTPUT = 'WRITE_ANALOG_OUTPUT';
export const WRITE_BINARY_VALUE = 'WRITE_BINARY_VALUE';
export const WRITE_BINARY_OUTPUT = 'WRITE_BINARY_OUTPUT';

export const SET_REQUESTED_POINTS = 'SET_REQUESTED_POINTS';
