const DATABASE_HOST = 'localhost';
const DATABASE_PORT = 27017;
const DATABASE_NAME = 'NAE55';
const DATABASE_TREND_NAME = 'trendsCollection';
const MAX_TREND_COLLECTION_SIZE = 10000;

module.exports = {
    DATABASE_HOST,
    DATABASE_PORT,
    DATABASE_NAME,
    DATABASE_TREND_NAME,
    MAX_TREND_COLLECTION_SIZE,
};
