const DATABASE_NAME = 'nae55v01.db';
const DATABASE_LOCATION = './SQLite3/db/';
const MAX_TREND_COLLECTION_SIZE = 100000000;
const TABLE_DAY_CONSUMPTION = 'dayConsumption';
const TABLE_TREND_DATA = 'trendData';
const TABLE_USERS = 'users';

module.exports = {
    DATABASE_NAME,
    DATABASE_LOCATION,
    MAX_TREND_COLLECTION_SIZE,
    TABLE_DAY_CONSUMPTION,
    TABLE_TREND_DATA,
    TABLE_USERS,
};
